image: ruby:2.4.0

clone:
  depth: full
  
options:
  docker: true
  size: 2x
  
pipelines:
  default:
    - step:
        name: 'Master Rails 5 Rspec'
        caches:
          - bundler
        services:
          - mysql
          - redis
        script:
          - bundle install
          - bundle exec rake db:create RAILS_ENV=test
          - bundle exec rake db:migrate RAILS_ENV=test
          - RAILS_ENV=test rspec
          - pipe: sonarsource/sonarcloud-scan:1.0.1
            variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
            variables:
                SONAR_TOKEN: ${SONAR_TOKEN}

definitions:
  caches:
    bundler: vendor/bundle
  services:
    redis:
      image: redis:3.2
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: pipelines
        MYSQL_ROOT_PASSWORD: root_user_password
        MYSQL_USER: test_user
        MYSQL_PASSWORD: test_user_password
    docker:
      memory: 4096