image: atlassian/default-image:3

clone:
  depth: full

definitions:
  caches:
    bundler: vendor/bundle
  services:
    redis:
      image: redis:3.2
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: groovepacks_test
        MYSQL_ROOT_PASSWORD: root_user_password
        MYSQL_USER: groovepacker
        MYSQL_PASSWORD: password
    docker:
      memory: 4096


options:
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        name: Rails 5 Rspec
        image: capsens/ruby-node-yarn:2.6.2
        caches:
          - bundler
        services:
          - mysql
          - redis
        script:
          - bundle install --path vendor/bundle
          - bundle binstubs --all
          - RAILS_ENV=test bundle exec rails db:create db:migrate
          - RAILS_ENV=test bundle exec rspec
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          - chmod +x ./cc-test-reporter
          - ./cc-test-reporter format-coverage --input-type simplecov --output coverage/codeclimate.json
          - ./cc-test-reporter upload-coverage --input coverage/codeclimate.json
          - pipe: sonarsource/sonarcloud-scan:2.0.0
            variables:
              EXTRA_ARGS: '-Dsonar.projectKey=groovepacker_groovepacker -Dsonar.organization=groove'
              SONAR_TOKEN: ${SONAR_TOKEN}
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
            variables:
              EXTRA_ARGS: '-Dsonar.projectKey=groovepacker_groovepacker -Dsonar.organization=groove'
              SONAR_TOKEN: ${SONAR_TOKEN}
  branches:
    master:
      - step:
          image: mcr.microsoft.com/playwright:v1.41.1-jammy
          name: Running Playwright tests
          script:
            - rm -rf *
            - git clone git@bitbucket.org:groovepacker/groovepackerautomation.git
            - cd groovepackerautomation
            - npm install
            - npx playwright install-deps
            - npm run legacy
          artifacts:
            paths:
              - .bitbucket/pipelines/groovepackerautomation/playwright-report/**
