<%
  @path = "#{Rubber.root}/config/database.yml"
%>

<%= Rubber.env %>:
  adapter: <%= YAML::load(File.open("#{Rubber.root}/config/database.yml"))["production"]["adapter"] %>
  encoding: utf8
  database: <%= rubber_env.db_name %>
  username: <%= 'root' %>
  password: <%= 'password' %>
  host: <%= 'localhost' %>
  pool: 5
