require 'rails_helper'

RSpec.describe GeneralSetting, type: :model do
  it 'Validate Barcode Length and Starting Value' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :save
    expect(generalsetting.starting_value).to eq('20000000')
    expect(generalsetting.starting_value.length).to eq(8)
  end

  it 'Send Low Inventory Alert Email' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :save
    expect(generalsetting.send_low_inventory_alert_email).to eq(true)
  end


  it 'Schedule import' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :save
    expect(generalsetting.scheduled_import).to eq(true)
  end
  
  it 'Send Low Inventory Alert Email' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :save
    expect(generalsetting.scheduled_import).to eq(true)
  end

  it 'Should import Orders Today' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    expect(generalsetting.should_import_orders_today).to eq(false)
  end

  it 'Should import Orders' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    expect(generalsetting.should_import_orders(DateTime.now)).to eq(false)
  end

  it 'Validate Params' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :save
    generalsetting.validate_params

    expect(generalsetting.packing_slip_orientation ).to eq('portrait')
    expect(generalsetting.max_time_per_item).to eq(10)
    expect(generalsetting.default_low_inventory_alert_limit).to eq(1)
    expect(generalsetting.inventory_tracking ).to eq(false)
    expect(generalsetting.time_to_send_email.to_s).to eq('2021-05-12 05:30:00 UTC')
    expect(generalsetting.time_to_import_orders.to_s).to eq('2021-05-12 05:30:00 UTC')
  end

  it 'Inventory State Change Check' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    generalsetting.run_callbacks :update
    expect(generalsetting.inventory_state_change_check).to eq(true)
  end
  
  it 'Should Send Email Today' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    expect(generalsetting.should_send_email_today).to eq(false)
  end
 
  it 'Should Send Email' do
    generalsetting = GeneralSetting.new(inventory_tracking: false, low_inventory_alert_email: false, low_inventory_email_address: "", hold_orders_due_to_inventory: false, conf_req_on_notes_to_packer: "always", send_email_for_packer_notes: "always", email_address_for_packer_notes: "kapiltest@yomail.com", created_at: "2021-03-25 10:20:05", updated_at: "2021-05-12 10:54:02", default_low_inventory_alert_limit: 1, send_email_on_mon: false, send_email_on_tue: false, send_email_on_wed: false, send_email_on_thurs: false, send_email_on_fri: false, send_email_on_sat: false, send_email_on_sun: false, time_to_send_email: "2021-05-12 05:30:00", product_weight_format: nil, packing_slip_size: "4 x 6", packing_slip_orientation: "portrait", packing_slip_message_to_customer: nil, import_orders_on_mon: false, import_orders_on_tue: false, import_orders_on_wed: false, import_orders_on_thurs: false, import_orders_on_fri: false, import_orders_on_sat: false, import_orders_on_sun: false, time_to_import_orders: "2021-05-12 05:30:00", scheduled_order_import: true, tracking_error_order_not_found: nil, tracking_error_info_not_found: nil, strict_cc: true, conf_code_product_instruction: "always", admin_email: nil, export_items: "standard_order_export", custom_field_one: "Custom 1", custom_field_two: "Custom 2", max_time_per_item: 10, export_csv_email: nil, show_primary_bin_loc_in_barcodeslip: false, time_zone: "19800", search_by_product: true, auto_detect: true, dst: true, stat_status: nil, cost_calculator_url: nil, schedule_import_mode: nil, master_switch: false, html_print: false, idle_timeout: 0.0, hex_barcode: false, from_import: "2000-01-01 00:00:00", to_import: "2000-01-01 23:59:00", multi_box_shipments: false, per_box_packing_slips: "manually", custom_user_field_one: nil, custom_user_field_two: nil, email_address_for_billing_notification: "kapiltest@yomail.com", display_kit_parts: false, remove_order_items: false, create_barcode_at_import: false, print_post_scanning_barcodes: false, print_packing_slips: false, print_ss_shipping_labels: false, per_box_shipping_label_creation: "per_box_shipping_label_creation_none", barcode_length: 8, starting_value: "2", show_sku_in_barcodeslip: true, print_product_barcode_labels: true)
    expect(generalsetting.should_send_email(DateTime.now)).to eq(false)
  end

end