# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at http://help.apm.scoutapp.com#environment-variables for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: gCZjykDqUxo6Qs7yc2kG

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error

  disabled_instruments:
    - "NetHttp"

  # name: Application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  name: GroovePacker [<%= Rails.env.titleize %>]

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true

production:
  <<: *defaults
  auto_instruments: true
  logs_monitor: true
  logs_ingest_key: e71f08e4-3d2e-45d3-b8e6-d2a4209ff784:1d36eb00-f643-453b-9923-660ee21f5bd1:5985860

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults
  auto_instruments: true
  monitor: false
