time_zone_names:
  Pacific/Tongatapu: +13:00:01
  Pacific/Auckland: +12:00:01
  Pacific/Fiji: +12:00:02
  Pacific/Guadalcanal: +11:00:01
  Asia/Vladivostok: +10:00:02
  Pacific/Port_Moresby: +10:00:01
  Australia/Melbourne: +10:00:05
  Australia/Hobart: +10:00:03
  Australia/Brisbane: +10:00:04
  Australia/Darwin: +09:30:02
  Australia/Adelaide: +09:30:01
  Asia/Yakutsk: +09:00:01
  Asia/Tokyo: +09:00:02
  Asia/Seoul: +09:00:03
  Asia/Ulaanbaatar: +08:00:01
  Asia/Taipei: +08:00:03
  Asia/Singapore: +08:00:04
  Australia/Perth: +08:00:02
  Asia/Hong_Kong: +08:00:05
  Asia/Krasnoyarsk: +07:00:01
  Asia/Jakarta: +07:00:02
  Asia/Rangoon: +06:30:01
  Asia/Dhaka: +06:00:04
  Asia/Almaty: +06:00:02
  Asia/Kathmandu: +05:45:01
  Asia/Colombo: +06:00:03
  Asia/Kolkata: +05:30:01
  Asia/Tashkent: +05:00:01
  Asia/Yekaterinburg: +05:00:02
  Asia/Kabul: +04:30:01
  Asia/Yerevan: +04:00:02
  Asia/Muscat: +04:00:03
  Asia/Tehran: +03:30:01
  Europe/Moscow: +03:00:05
  Africa/Nairobi: +03:00:03
  Asia/Kuwait: +03:00:04
  Asia/Baghdad: +03:00:02
  Africa/Johannesburg: +02:00:01
  Asia/Jerusalem: +02:00:02
  Europe/Helsinki: +02:00:04
  Africa/Cairo: +02:00:05
  Europe/Bucharest: +02:00:06
  Europe/Athens: +02:00:03
  Africa/Algiers: +01:00:01
  Europe/Sarajevo: +01:00:04
  Europe/Brussels: +01:00:03
  Europe/Belgrade: +01:00:05
  Europe/Amsterdam: +01:00:02
  Africa/Monrovia: +00:00:01 
  Europe/London: +00:00:02
  Atlantic/Cape_Verde: -01:00:01
  Atlantic/Azores: -01:00:02
  Atlantic/South_Georgia: -02:00:01
  America/Godthab: -03:00:01
  America/Argentina/Buenos_Aires: -03:00:02
  America/Sao_Paulo: -03:00:03
  America/St_Johns: -03:30:01
  America/Santiago: -04:00:01
  America/Caracas: -04:00:02
  America/Halifax: -04:00:03
  America/Indiana/Indianapolis: -05:00:02
  America/New_York: -05:00:03
  America/Bogota: -05:00:01
  America/Regina: -06:00:03
  America/Mexico_City: -06:00:02
  America/Chicago: -06:00:04
  America/Guatemala: -06:00:01
  America/Denver: -07:00:03
  America/Chihuahua: -07:00:02
  America/Phoenix: -07:00:01
  America/Los_Angeles: -08:00:01
  America/Juneau: -09:00:01
  Pacific/Honolulu: -10:00:01
  Pacific/Midway: -11:00:01
