time_zones:
  (GMT+13:00) Tonga Standard Time (Nuku'alofa): +13:00:01
  (GMT+12:00) New Zealand Standard Time (Auckland, Wellington): +12:00:01
  (GMT+12:00) Fiji Islands Standard Time (Fiji Islands): +12:00:02
  (GMT+11:00) Central Pacific Standard Time (Solomon Islands): +11:00:01
  (GMT+10:00) West Pacific Standard Time (Guam, Port Moresby): +10:00:01
  (GMT+10:00) Vladivostok Standard Time (Vladivostok): +10:00:02
  (GMT+10:00) Tasmania Standard Time (Hobart): +10:00:03
  (GMT+10:00) E. Australia Standard Time (Brisbane): +10:00:04
  (GMT+10:00) A.U.S. Eastern Standard Time (Canberra, Melbourne, Sydney): +10:00:05
  (GMT+09:30) Cen. Australia Standard Time (Adelaide): +09:30:01
  (GMT+09:30) A.U.S. Central Standard Time (Darwin): +09:30:02
  (GMT+09:00) Yakutsk Standard Time (Yakutsk): +09:00:01
  (GMT+09:00) Tokyo Standard Time  (Osaka, Sapporo, Tokyo): +09:00:02
  (GMT+09:00) Korea Standard Time  (Seoul): +09:00:03
  (GMT+08:00) North Asia East Standard Time (Irkutsk, Ulaanbaatar): +08:00:01
  (GMT+08:00) W. Australia Standard Time (Perth): +08:00:02
  (GMT+08:00) Taipei Standard Time (Taipei): +08:00:03
  (GMT+08:00) Singapore Standard Time  (Kuala Lumpur, Singapore): +08:00:04
  (GMT+08:00) China Standard Time (Beijing, Hong Kong SAR): +08:00:05
  (GMT+07:00) North Asia Standard Time (Krasnoyarsk): +07:00:01
  (GMT+07:00) S.E. Asia Standard Time (Bangkok, Hanoi, Jakarta): +07:00:02
  (GMT+06:30) Myanmar Standard Time (Yangon Rangoon): +06:30:01
  (GMT+06:00) N. Central Asia Standard Time (Almaty, Novosibirsk): +06:00:02
  (GMT+06:00) Sri Lanka Standard Time  Sri (Jayawardenepura): +06:00:03
  (GMT+06:00) Central Asia Standard Time (Astana, Dhaka): +06:00:04
  (GMT+05:45) Nepal Standard Time  (Kathmandu): +05:45:01
  (GMT+05:30) India Standard Time  (Chennai, Kolkata, Mumbai, New Delhi): +05:30:01
  (GMT+05:00) West Asia Standard Time (Islamabad, Karachi, Tashkent): +05:00:01
  (GMT+05:00) Ekaterinburg Standard Time (Ekaterinburg): +05:00:02
  (GMT+04:30) Transitional Islamic State of Afghanistan Standard Time (Kabul): +04:30:01
  (GMT+04:00) Caucasus Standard Time (Baku, Tbilisi, Yerevan): +04:00:02
  (GMT+04:00) Arabian Standard Time (Abu Dhabi, Muscat): +04:00:03
  (GMT+03:30) Iran Standard Time (Tehran): +03:30:01
  (GMT+03:00) Arabic Standard Time (Baghdad): +03:00:02
  (GMT+03:00) E. Africa Standard Time  (Nairobi): +03:00:03
  (GMT+03:00) Arab Standard Time (Kuwait, Riyadh): +03:00:04
  (GMT+03:00) Russian Standard Time (Moscow, St. Petersburg, Volgograd): +03:00:05
  (GMT+02:00) South Africa Standard Time (Harare, Pretoria): +02:00:01
  (GMT+02:00) Israel Standard Time (Jerusalem): +02:00:02
  (GMT+02:00) GTB Standard Time (Athens, Istanbul, Minsk): +02:00:03
  (GMT+02:00) FLE Standard Time (Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius): +02:00:04
  (GMT+02:00) Egypt Standard Time (Cairo): +02:00:05
  (GMT+02:00) E. Europe Standard Time  (Bucharest): +02:00:06
  (GMT+01:00) W. Central Africa Standard Time  (West Central Africa): +01:00:01
  (GMT+01:00) W. Europe Standard Time (Amsterdam, Berlin, Rome): +01:00:02
  (GMT+01:00) Romance Standard Time (Brussels, Copenhagen, Madrid, Paris): +01:00:03
  (GMT+01:00) Central European Standard Time (Sarajevo, Warsaw): +01:00:04
  (GMT+01:00) Central Europe Standard Time (Belgrade, Budapest, Prague): +01:00:05
  (GMT+00:00) Greenwich Standard Time  (Casablanca, Monrovia): +00:00:01 
  (GMT+00:00) GMT Standard Time (London): +00:00:02
  (GMT-01:00) Cape Verde Standard Time (Cape Verde Islands): -01:00:01
  (GMT-01:00) Azores Standard Time (Azores): -01:00:02
  (GMT-02:00) Mid-Atlantic Standard Time (Mid-Atlantic): -02:00:01
  (GMT-03:00) Greenland Standard Time  (Greenland): -03:00:01
  (GMT-03:00) S.A. Eastern Standard Time (Buenos Aires, Georgetown): -03:00:02
  (GMT-03:00) E. South America Standard Time (Brasilia): -03:00:03
  (GMT-03:30) Newfoundland and Labrador Standard Time (Newfoundland): -03:30:01
  (GMT-04:00) Pacific S.A. Standard Time (Santiago): -04:00:01
  (GMT-04:00) S.A. Western Standard Time (Caracas, La Paz): -04:00:02
  (GMT-04:00) Atlantic Standard Time (Atlantic Time (Canada)): -04:00:03
  (GMT-05:00) S.A. Pacific Standard Time (Bogota, Lima, Quito): -05:00:01
  (GMT-05:00) U.S. Eastern Standard Time (Indiana): -05:00:02
  (GMT-05:00) Eastern Standard Time (Eastern Time (US and Canada)): -05:00:03
  (GMT-06:00) Central America Standard Time (Central America): -06:00:01
  (GMT-06:00) Mexico Standard Time (Guadalajara, Mexico City, Monterrey): -06:00:02
  (GMT-06:00) Canada Central Standard Time (Saskatchewan): -06:00:03
  (GMT-06:00) Central Standard Time (Central Time (US and Canada)): -06:00:04
  (GMT-07:00) U.S. Mountain Standard Time (Arizona): -07:00:01
  (GMT-07:00) Mexico Standard Time 2 (Chihuahua, La Paz, Mazatlan): -07:00:02
  (GMT-07:00) Mountain Standard Time (Mountain Time (US and Canada)): -07:00:03
  (GMT-08:00) Pacific Standard Time (Pacific Time (US and Canada), Tijuana): -08:00:01
  (GMT-09:00) Alaskan Standard Time (Alaska): -09:00:01
  (GMT-10:00) Hawaiian Standard Time (Hawaii): -10:00:01
  (GMT-11:00) Samoa Standard Time  (Midway Island, Samoa): -11:00:01
  (GMT-12:00) Dateline Standard Time  (International Date Line West): -12:00:01
