#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'

# Specify pid file directory
# ARGV << "--pid-dir=#{Rails.root}/pids"

Delayed::Command.new(ARGV).daemonize
