class ProductsController < ApplicationController
  include ProductConcern

  def import_products
    @store = Store.find(params[:id])
    importservice = init_products_import_service(@store)
    @result = importservice.import_products

    render json: @result
  end

  def import_images
    @store = Store.find(params[:id])
    @result = @product_service.import_images(@store)

    render json: @result
  end

  # PS:Where is this used?
  def import_product_details
    # if current_user.can?('import_products')
    #   @store = Store.find(params[:store_id])
    #   @amazon_credentials = AmazonCredentials.where(:store_id => @store.id)

    #   if @amazon_credentials.length > 0
    #     @credential = @amazon_credentials.first

    #     require 'mws-connect'

    #     mws = Mws.connect(
    #       merchant: @credential.merchant_id,
    #       access: ENV['AMAZON_MWS_ACCESS_KEY_ID'],
    #       secret: ENV['AMAZON_MWS_SECRET_ACCESS_KEY']
    #     )
    #     products_api = mws.products.get_matching_products_for_id(:marketplace_id => @credential.marketplace_id,
    #                                                              :id_type => 'SellerSKU', :id_list => ['T-TOOL'])
    #     require 'active_support/core_ext/hash/conversions'
    #     product_hash = Hash.from_xml(products_api.to_s)
    #     # product_hash = from_xml(products_api)
    #     raise
    #     # response = mws.orders.get_matching_product_for_id :id_type=>'SellerSKU', :seller_sku => ["12345678"],
    #     #   :marketplace_id => @credential.marketplace_id
    #     # # response = mws.orders.list_orders :last_updated_after => 2.months.ago,
    #     # #   :order_status => ['Unshipped', 'PartiallyShipped']
    #     # response.products
    #     @products = Product.where(:store_id => params[:store_id])
    #     @products.each do |product|
    #       #import_amazon_product_details(mws, @credential, product.id)
    #     end
    #   end

    # end
  end

  # def requestamazonreport
  #   @amazon_credentials = AmazonCredentials.where(:store_id => params[:id])
  #   @result = Hash.new
  #   @result['status'] = false
  #   if @amazon_credentials.length > 0

  #     @credential = @amazon_credentials.first

  #     mws = MWS.new(:aws_access_key_id => ENV['AMAZON_MWS_ACCESS_KEY_ID'],
  #                   :secret_access_key => ENV['AMAZON_MWS_SECRET_ACCESS_KEY'],
  #                   :seller_id => @credential.merchant_id,
  #                   :marketplace_id => @credential.marketplace_id)

  #     response = mws.reports.request_report :report_type => '_GET_MERCHANT_LISTINGS_DATA_'
  #     @credential.productreport_id = response.report_request_info.report_request_id
  #     @credential.productgenerated_report_id = nil

  #     if @credential.save
  #       @result['status'] = true
  #       @result['requestedreport_id'] = @credential.productreport_id
  #     end

  #   end

  #   respond_to do |format|
  #     format.json { render json: @result }
  #   end
  # end

  # def checkamazonreportstatus
  #   @amazon_credentials = AmazonCredentials.where(:store_id => params[:id])
  #   @result = Hash.new
  #   @result['status'] = false
  #   report_found = false
  #   if @amazon_credentials.length > 0

  #     @credential = @amazon_credentials.first

  #     mws = MWS.new(:aws_access_key_id => ENV['AMAZON_MWS_ACCESS_KEY_ID'],
  #                   :secret_access_key => ENV['AMAZON_MWS_SECRET_ACCESS_KEY'],
  #                   :seller_id => @credential.merchant_id,
  #                   :marketplace_id => @credential.marketplace_id)

  #     @report_list = mws.reports.get_report_request_list
  #     @report_list.report_request_info.each do |report_request|
  #       if report_request.report_request_id == @credential.productreport_id
  #         report_found = true
  #         if report_request.report_processing_status == '_SUBMITTED_'
  #           @result['status'] = true
  #           @result['report_status'] = 'Report has been submitted successfully. '+
  #             'It is still being generated by the server.'
  #         elsif report_request.report_processing_status == '_DONE_'
  #           @result['report_status'] = 'Report is generated successfully.'

  #           @credential.productgenerated_report_id = report_request.generated_report_id
  #           @credential.productgenerated_report_date = report_request.completed_date
  #           if @credential.save
  #             @result['status'] = true
  #             @result['requestedreport_id'] = @credential.productreport_id
  #             @result['generated_report_id'] = report_request.generated_report_id
  #             @result['generated_report_date'] = report_request.completed_date
  #           end
  #         elsif report_request.report_processing_status == '_INPROGRESS_'
  #           @result['status'] = true
  #           @result['report_status'] = 'Report is in progress. It will be ready in few moments.'
  #         else
  #           @result['response'] = report_request
  #           #store generated report id
  #         end
  #       end
  #     end

  #     if !report_found
  #       @result['status'] = true
  #       @result['report_status'] = 'Report is not found. Please check back in few moments.'
  #     end
  #   end

  #   respond_to do |format|
  #     format.json { render json: @result }
  #   end
  # end

  # Get list of products based on limit and offset. It is by default sorted by updated_at field
  # If sort parameter is passed in then the corresponding sort filter will be used to sort the list
  # The expected parameters in params[:sort] are 'updated_at', name', 'sku', 'status', 'barcode', 'location_primary'
  # and quantity. The API supports to provide order of sorting namely ascending or descending. The parameter can be
  # passed in using params[:order] = 'ASC' or params[:order] ='DESC' [Note: Caps letters] By default, if no order is mentioned,
  # then the API considers order to be descending.The API also supports a product status filter.
  # The filter expects one of the following parameters in params[:filter] 'all', 'active', 'inactive', 'new'.
  # If no filter is passed, then the API will default to 'active'
  # if you would like to get Kits, specify params[:is_kit] to 1. it will return product kits and the corresponding skus
  #
  def index
    @products = do_getproducts(params)
    @result = @result.merge({ 'products' => make_products_list(@products),
                              'products_count' => get_products_count()
                            })
    render json: @result
  end

  def create
    @result = Product.create_new_product(@result, current_user)
    
    render json: @result
  end

  def print_receiving_label
    @products = list_selected_products(params)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        time = Time.now
        file_name = 'receiving_label_'+time.strftime('%d_%b_%Y')
        @result['receiving_label_path'] = '/pdfs/'+ file_name + '.pdf'
        render :pdf => file_name,
               :template => 'products/print_receiving_label',
               :orientation => 'portrait',
               :page_height => '6in',
               :save_only => true,
               :page_width => '4in',
               :margin => {:top => '1',
                           :bottom => '0',
                           :left => '2',
                           :right => '2'},
               :handlers => [:erb],
               :formats => [:html],
               :save_to_file => Rails.root.join('public', 'pdfs', "#{file_name}.pdf")

        render json: @result
      }
    end
  end

  def generate_barcode
    @products = list_selected_products(params)
    @products.each { |product| @result = product.generate_barcode(@result) }

    render json: @result
  end

  # For search pass in parameter params[:search] and a params[:limit] and params[:offset].
  # If limit and offset are not passed, then it will be default to 10 and 0
  def search
    unless params[:search].blank?
      @products = do_search(params, false)
      @result = @result.merge({ 'products' => make_products_list(@products['products']),
                                'products_count' => get_products_count
                              })
      @result['products_count']['search'] = @products['count']
    else
      @result['status'] = false
      @result['message'] = 'Improper search string'
    end

    render json: @result
  end

  def scan_per_product
    execute_scan_per_product

    render json: @result
  end

  def change_product_status
    #execute_groove_bulk_action(activity)
    execute_groove_bulk_action('status_update')
  end

  def delete_product
    #execute_groove_bulk_action(activity)
    execute_groove_bulk_action('delete')
  end

  def duplicate_product
    #execute_groove_bulk_action(activity)
    execute_groove_bulk_action('duplicate')
  end

  def show
    @product = nil
    params[:id] = nil if params[:id]=="null"
    if params[:id].present?
      @product = Product.find_by_id(params[:id])
    else
      prod_barcodes = ProductBarcode.where(:barcode => params[:barcode])
      if prod_barcodes.length > 0
        @product = prod_barcodes.first.product
      end
    end
    if @product.present?
      @product.reload
      store_id = @product.store_id
      stores = Store.where(:id => store_id)
      if !stores.nil?
        @store = stores.first
      end
      general_setting = GeneralSetting.all.first
      scan_pack_setting = ScanPackSetting.all.first
      amazon_products = AmazonCredentials.where(:store_id => store_id)
      unless amazon_products.blank?
        @amazon_product = amazon_products.first
      end

      @result['product'] = Hash.new
      @result['product']['amazon_product'] = @amazon_product
      @result['product']['store'] = @store
      @result['product']['sync_option'] = @product.sync_option.attributes rescue nil
      @result['product']['access_restrictions'] = AccessRestriction.last rescue nil
      @result['product']['basicinfo'] = @product.attributes
      @result['product']['basicinfo']['weight_format'] = @product.get_show_weight_format
      @result['product']['basicinfo']['contains_intangible_string'] = @product.contains_intangible_string
      @result['product']['product_weight_format'] = GeneralSetting.get_product_weight_format
      @result['product']['weight'] = @product.get_weight
      @result['product']['shipping_weight'] = @product.get_shipping_weight
      @result['product']['skus'] = @product.product_skus.order("product_skus.order ASC")
      @result['product']['cats'] = @product.product_cats
      @result['product']['spl_instructions_4_packer'] = @product.spl_instructions_4_packer
      @result['product']['images'] = @product.base_product.product_images.order("product_images.order ASC")
      @result['product']['barcodes'] = @product.product_barcodes.order("product_barcodes.order ASC")
      @result['product']['inventory_warehouses'] = []

      @product.product_inventory_warehousess.each do |inv_wh|
        if UserInventoryPermission.where(
          :user_id => current_user.id,
          :inventory_warehouse_id => inv_wh.inventory_warehouse_id,
          :see => true
        ).length > 0
          inv_wh_result = Hash.new
          inv_wh_result['info'] = inv_wh.attributes
          inv_wh_result['info']['quantity_on_hand'] = inv_wh.quantity_on_hand
          unless general_setting.low_inventory_alert_email
            inv_wh_result['info']['product_inv_alert'] = false
          end
          unless inv_wh_result['info']['product_inv_alert']
            inv_wh_result['info']['product_inv_alert_level'] = general_setting.default_low_inventory_alert_limit
          end
          inv_wh_result['warehouse_info'] = nil
          unless inv_wh.inventory_warehouse_id.nil?
            inv_wh_result['warehouse_info'] = InventoryWarehouse.find(inv_wh.inventory_warehouse_id)
          end
          @result['product']['inventory_warehouses'] << inv_wh_result
        end
      end
      #@result['product']['productkitskus'] = @product.product_kit_skuss
      @result['product']['productkitskus'] = []
      if @product.is_kit
        @product.product_kit_skuss.each do |kit|
          option_product = Product.find(kit.option_product_id)

          kit_sku = Hash.new
          kit_sku['name'] = option_product.name
          kit_sku['product_status'] = option_product.status
          if option_product.product_skus.length > 0
            kit_sku['sku'] = option_product.primary_sku
          end
          kit_sku['qty'] = kit.qty
          kit_sku['available_inv'] = 0
          kit_sku['qty_on_hand'] = 0
          option_product.product_inventory_warehousess.each do |inventory|
            kit_sku['available_inv'] += inventory.available_inv.to_i
            kit_sku['qty_on_hand'] += inventory.quantity_on_hand.to_i
          end
          kit_sku['packing_order'] = kit.packing_order
          kit_sku['option_product_id'] = option_product.id
          @result['product']['productkitskus'].push(kit_sku)
        end
        @result['product']['productkitskus'] =
          @result['product']['productkitskus'].sort_by { |hsh| hsh['packing_order'] }
        @result['product']['product_kit_activities'] = @product.product_kit_activities
        @result['product']['unacknowledged_kit_activities'] = @product.unacknowledged_kit_activities
      end

      if @product.product_skus.length > 0
        @result['product']['pendingorders'] = Order.where(:status => 'awaiting').where(:status => 'onhold').
          where(:sku => @product.product_skus.first.sku)
      else
        @result['product']['pendingorders'] = nil
      end
    end

    render json: @result
  end

  def add_product_to_kit
    #@kit is coming from find_kit_product method of products concern
    @result = ProductKitSkus.app_product_to_kit(@kit, params, @result) if check_if_not_a_kit

    render json: @result
  end

  def remove_products_from_kit
    #@kit is coming from find_kit_product method of products concern
    @result = ProductKitSkus.remove_products_from_kit(@kit, params, @result) if check_if_not_a_kit
    
    render json: @result
  end

  def update
    @result = gp_products_module.update_product_attributes
    
    render json: @result
  end

  #params[:id]
  def generate_barcode_slip
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf {
        render :pdf => "file_name",
               :template => 'products/generate_barcode_slip.html.erb',
               :orientation => 'Portrait',
               :page_height => '1in',
               :page_width => '3in',
               :margin => {:top => '0', :bottom => '0', :left => '0', :right => '0'}
      }
    end
  end

  def update_product_list
    result = Product.update_product_list(params, @result)

    render json: @result
  end

  #This action will remove the entry for this product (the Alias) and the SKU of this new
  #product will be added to the list of skus for the existing product that the user is linking it to.
  #Any product can be turned into an alias, it doesn’t have to have the status of new, although most if the time it probably will.
  #The operation can not be undone.
  #If you had a situation where the newly imported product was actually the one you wanted to keep you could
  #find the original product and make it an alias of the new product...
  def set_alias
    product_aliasing.set_alias

    render json: @result
  end

  def add_image
    product = Product.find(params[:id])
    add_new_image(product)
    
    render json: @result
  end

  #input params[:id] gives product id params[:inv_wh_id] gives inventory warehouse id
  #params[:inventory_count] contains the inventory count from the recount
  #params[:method] this can contain two options: 'recount' or 'receive'
  #PUT request and it updates the available inventory if method is recount
  # or adds to the available inventory if method is receive if the product is
  #not associated with the inventory warehouse, then it automatically associates it and
  #sets the value.
  def adjust_available_inventory
    unless params[:id].nil? || params[:inv_wh_id].nil? || params[:method].nil?
      result = ProductInventoryWarehouses.adjust_available_inventory(params, result)
    else
      @result['status'] &= false
      @result['error_messages'].push('Cannot recount inventory without product id and inventory_warehouse_id')
    end
    render json: @result
  end

  def generate_products_csv
    if current_user.can? 'create_backups'
      @result = generate_csv(@result)
    else
      @result['status'] = false
      @result['messages'].push('You do not have enough permissions to create backup csv')
    end
    @result = generate_error_csv(@result) unless @result['status']
    
    render json: @result
  end

  def update_intangibleness
    Product.update_action_intangibleness(params)

    render json: @result
  end

  def update_image
    @result['status'] = ProductImage.update_image(params)
    render json: @result
  end

  def sync_with
    @result['status'] = SyncOption.create_update_sync_option(params)
    render json: @result
  end

  private
  def execute_groove_bulk_action(activity)
    GrooveBulkActions.execute_groove_bulk_action(activity, params, current_user)

    render json: @result
  end
end
