---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: webinp01
  domain: groovepacks.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-a80adbce
  image_type: m1.small
  image_id: ami-e5582d8c
  security_groups:
  - groovepacks_production_default
  - groovepacks_production_web
  - groovepacks_production_webinp01
  - groovepacks_production_haproxy
  - groovepacks_production_collectd
  - groovepacks_production_monit
  external_host: ec2-23-21-16-43.compute-1.amazonaws.com
  external_ip: 23.21.16.43
  internal_host: ip-10-164-63-215.ec2.internal
  internal_ip: 10.164.63.215
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: dbinp01
  domain: groovepacks.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-843e5af9
  image_type: m1.small
  image_id: ami-e5582d8c
  security_groups:
  - groovepacks_production_default
  - groovepacks_production_dbinp01
  - groovepacks_production_db
  - groovepacks_production_mysql
  - groovepacks_production_mysql_master
  - groovepacks_production_collectd
  - groovepacks_production_monit
  external_host: ec2-54-234-22-126.compute-1.amazonaws.com
  external_ip: 54.234.22.126
  internal_host: ip-10-114-214-122.ec2.internal
  internal_ip: 10.114.214.122
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: appinp01
  domain: groovepacks.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-47594c23
  image_type: m1.small
  image_id: ami-e5582d8c
  security_groups:
  - groovepacks_production_default
  - groovepacks_production_appinp01
  - groovepacks_production_app
  - groovepacks_production_passenger
  - groovepacks_production_apache
  - groovepacks_production_collectd
  - groovepacks_production_monit
  external_host: ec2-54-234-10-27.compute-1.amazonaws.com
  external_ip: 54.234.10.27
  internal_host: ip-10-60-39-136.ec2.internal
  internal_ip: 10.60.39.136
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
